# Generated by Django 3.2.5 on 2022-01-13 03:37
from django.db import migrations, models
#Model defines Migration
#Dependencies to model migration
class Migration(migrations.Migration):
    dependencies = [
        (‘blog’, ‘0001_initial’),
    ]
    operations = [
        #Fields of the model: model name, name
        migrations.AddField(
            model_name=‘blog’,
            name=‘image’,
            field=models.ImageField(default=False, upload_to=‘blog/images/’),
        ),
    ]
